const UK = [
  {Country:'United Kingdom', 'Quarantine on arrival':'0 Day', 'Person 1 Entry Info':'n/a'},
  {Country:'Austria', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/austria/entry-requirements">Link</a>'},
  {Country:'Croatia', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'Cyprus', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'Czech Republic', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'Denmark', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'Estonia', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'Finland', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'Germany', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'Gibraltar', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'Greece', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'Hungary', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'Iceland', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'Ireland', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'Italy', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'Latvia', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'Liechtenstein', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'Lithuania', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'Norway', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'Poland', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'Portugal (only The Azores and Madeira)', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'San Marino', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'Slovakia', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'Slovenia', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'Switzerland', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'Turkey', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'Antigua & Barbuda', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'Barbados', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'Bermuda', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'Canada', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'Cayman Islands', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'Cuba', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'Curaçao', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'Dominica', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'Falkland Islands', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'Grenada', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'Guadeloupe', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'Jamaica', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'Martinique', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'South Georgia & the South Sandwich Islands', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'St Kitts and Nevis', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'St Lucia', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'St Maarten', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'St Martin and St Barthélemy', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'St Pierre and Miquelon', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'St Vincent and The Grenadines', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'Trinidad and Tobago', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'Australia', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'British Indian Ocean Territory', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'Brunei', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'Cambodia', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'Cook Islands', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'Fiji', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'French Polynesia', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'Hong Kong', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'Japan', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'Laos', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'Macao', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'Malaysia', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'New Caledonia', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'New Zealand', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'Samoa', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'Singapore', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'South Korea', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'Sri Lanka', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'Taiwan', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'Thailand', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'Vietnam', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'Wallis and Futuna', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'Reunion', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'St Helena, Ascension and Tristan da Cunha', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'British Antarctic Territory', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
 ];
const USA = [
  {Country:'USA', 'Quarantine on arrival':'Dependent on State', 'Person 1 Entry Info':'<a href="https://www.cdc.gov/coronavirus/2019-ncov/travelers/from-other-countries.html">Link</a>'},
  {Country:'French Polynesia', 'Quarantine on arrival':'Requires proof of negative test', 'Person 1 Entry Info':'<a href="https://fj.usembassy.gov/u-s-citizen-services/covid-19-information/">Link</a>'},
  {Country:'Antigua and Barbuda', 'Quarantine on arrival':'Test required', '<a href="https://visitantiguabarbuda.com/travel-advisory/">Link</a>'},
  {Country:'Armenia', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'Aruba', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'Australia', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'Austria', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'Azerbaijan', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'Bahrain', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'Barbados', 'Quarantine on arrival':'Test and quarantine required', 'Person 1 Entry Info':'<a href+"https://bb.usembassy.gov/u-s-citizen-services/covid-19-information/">Link</a>'},
  {Country:'Belarus', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'Belgium', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'Benin', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'Bermuda', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'Bonaire, Sint Eustatius and Saba', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'Bosnia and Herzegovina', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'Botswana', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'British Virgin Islands', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'Bulgaria', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'Burma (Myanmar)', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'Cambodia', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'Cameroon', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'Canada', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
  {Country:'Cayman Islands', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Chad', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Chile', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Comoros', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Cote dIvoire', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Croatia', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Curacao', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Cyprus', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Czech Republic', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Denmark', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Djibouti', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Dominica', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Ecuador', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Equatorial Guinea', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Eritrea', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Estonia', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Finland', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'France', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'French West Indies', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Gabon', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Georgia', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Germany', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Ghana', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Greece', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Grenada', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Guinea', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Guinea-Bissau', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Hungary', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Iceland', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Ireland', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Israel, The West Bank and Gaza', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Italy', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Jamaica', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Japan', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Jordan', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Kenya', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Kuwait', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Laos', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Latvia', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Lebanon', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Lesotho', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Liberia', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Liechtenstein', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Lithuania', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Luxembourg', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Madagascar', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Malaysia', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Maldives', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Malta', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Marshall Islands', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Mauritania', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Micronesia', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Moldova', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Montenegro', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Montserrat', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Morocco', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Nauru', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'<a href="https://fj.usembassy.gov/u-s-citizen-services/covid-19-information/">Link</a>'},
{Country:'Nepal', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Netherlands', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'New Caledonia', 'Quarantine on arrival':'14 days', 'Person 1 Entry Info':'<a href="https://fj.usembassy.gov/u-s-citizen-services/covid-19-information/">Link</a>'},
{Country:'Niger', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Nigeria', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'North Macedonia', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Norway', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Pakistan', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Palau', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Papua New Guinea', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Paraguay', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Philippines', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Poland', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Portugal', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Qatar', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Republic of the Congo', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Romania', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Rwanda', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Saint Kitts and Nevis', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Saint Lucia', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Saint Vincent and The Grenadines', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Samoa', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Senegal', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Serbia', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Seychelles', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Sierra Leone', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Singapore', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Sint Maarten', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Slovakia', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Slovenia', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Solomon Island', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'South Africa', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'South Korea', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Sri Lanka', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Sudan', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Suriname', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Sweden', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Switzerland', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Tanzania', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'The Gambia', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Timor-Leste', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Togo', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Trinidad and Tobago', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Tunisia', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Turkey', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Turks and Caicos Islands', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Uganda', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Ukraine', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'United Arab Emirates', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'United Kingdom', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Uruguay', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Uzbekistan', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Vanuatu', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Vietnam', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Zambia', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Zimbabwe', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Mozambique', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
 ];
// const EU = [
//     {Country:'United Kingdom', 'Quarantine on arrival':'14 Day', 'Person 1 Entry Info':'visit gov.uk/'},
//     {Country:'Croatia', 'Quarantine on arrival':'14 Day', 'Person 1 Entry Info':'visit us.gov.croatia'},
//     {Country:'Ireland', 'Quarantine on arrival':'0 Day', 'Person 1 Entry Info':'visit gov.uk/'},
//     {Country:'European Union', 'Quarantine on arrival':'0 Day', 'Person 1 Entry Info':'visit gov.uk/'},
//  ];
// const IRL = [
//     {Country:'United Kingdom', 'Quarantine on arrival':'14 Day', 'Person 1 Entry Info':'visit gov.uk/'},
//     {Country:'European Union', 'Quarantine on arrival':'0 Day', 'Person 1 Entry Info':'visit gov.uk/'},
//     {Country:'Ireland', 'Quarantine on arrival':'0 Day', 'Person 1 Entry Info':'visit gov.uk/'}
//  ];

const options = ["UK", "USA"];
