const UK = [
  {Country:'United Kingdom', 'Quarantine on arrival':'n/a', 'Person 1 Entry Info':'n/a'},
  {Country:'Austria', 'Quarantine on arrival':'None', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/austria/entry-requirements">Link</a>'},
  {Country:'Croatia', 'Quarantine on arrival':'None', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/croatia/entry-requirements">Link</a>'},
  {Country:'Cyprus', 'Quarantine on arrival':'PCR 72hrs prior', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/cyprus/entry-requirements">Link</a>'},
  {Country:'Czech Republic', 'Quarantine on arrival':'None', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/czech-republic/entry-requirements">Link</a>'},
  {Country:'Denmark', 'Quarantine on arrival':'None', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/denmark/entry-requirements">Link</a>'},
  {Country:'Estonia', 'Quarantine on arrival':'None', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/estonia/entry-requirements">Link</a>'},
  {Country:'Germany', 'Quarantine on arrival':'None', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/germany/entry-requirements">Link</a>'},
  {Country:'Gibraltar', 'Quarantine on arrival':'None', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/gibraltar/entry-requirements">Link</a>'},
  {Country:'Greece', 'Quarantine on arrival':'Complex', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/greece/entry-requirements">Link</a>'},
  {Country:'Hungary', 'Quarantine on arrival':'2 x PCR prior', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/hungary/entry-requirements">Link</a>'},
  {Country:'Iceland', 'Quarantine on arrival':'PCR on arrival', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/iceland/entry-requirements">Link</a>'},
  {Country:'Ireland', 'Quarantine on arrival':'14 Day', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/ireland/entry-requirements">Link</a>'},
  {Country:'Italy', 'Quarantine on arrival':'None', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/italy/entry-requirements">Link</a>'},
  {Country:'Latvia', 'Quarantine on arrival':'14 Day', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/latvia/entry-requirements">Link</a>'},
  {Country:'Liechtenstein', 'Quarantine on arrival':'None', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/liechtenstein/entry-requirements">Link</a>'},
  {Country:'Lithuania', 'Quarantine on arrival':'None', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/lithuania/entry-requirements">Link</a>'},
  {Country:'Norway', 'Quarantine on arrival':'None', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/norway/entry-requirements">Link</a>'},
  {Country:'Poland', 'Quarantine on arrival':'None', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/poland/entry-requirements">Link</a>'},
  {Country:'Portugal (only The Azores and Madeira)', 'Quarantine on arrival':'Complex', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/portugal/entry-requirements">Link</a>'},
  {Country:'San Marino', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/san-marino/entry-requirements">Link</a>'},
  {Country:'Slovakia', 'Quarantine on arrival':'None', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/slovakia/entry-requirements">Link</a>'},
  {Country:'Slovenia', 'Quarantine on arrival':'None', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/slovenia/entry-requirements">Link</a>'},
  {Country:'Switzerland', 'Quarantine on arrival':'None', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/poland/entry-requirements">Link</a>'},
  {Country:'Turkey', 'Quarantine on arrival':'None', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/turkey/entry-requirements">Link</a>'},
  {Country:'Antigua and Barbuda', 'Quarantine on arrival':'Complex', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/antigua-and-barbuda/entry-requirements">Link</a>'},
  {Country:'Barbados', 'Quarantine on arrival':'PCR prior, complex', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/barbados/entry-requirements">Link</a>'},
  {Country:'Bermuda', 'Quarantine on arrival':'Complex', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/bermuda/entry-requirements">Link</a>'},
  {Country:'Cuba', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/cuba/entry-requirements">Link</a>'},
  {Country:'Curaçao', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/curacao/entry-requirements">Link</a>'},
  {Country:'Dominica', 'Quarantine on arrival':'PCR Prior', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/dominica/entry-requirements">Link</a>'},
  {Country:'Falkland Islands', 'Quarantine on arrival':'14 Days', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/falkland-islands/entry-requirements">Link</a>'},
  {Country:'Grenada', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/grenada/entry-requirements">Link</a>'},
  {Country:'Guadeloupe', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/guadeloupe/entry-requirements">Link</a>'},
  {Country:'Jamaica', 'Quarantine on arrival':'Complex', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/jamaica/entry-requirements">Link</a>'},
  {Country:'Martinique', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/martinique/entry-requirements">Link</a>'},
  {Country:'South Georgia and the South Sandwich Islands', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/south-georgia-and-south-sandwich-islands/entry-requirements">Link</a>'},
  {Country:'St Lucia', 'Quarantine on arrival':'Complex', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/st-lucia/entry-requirements">Link</a>'},
  {Country:'St Maarten', 'Quarantine on arrival':'PCR 72hrs prior', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/st-maarten/entry-requirements">Link</a>'},
  {Country:'St Martin and St Barthélemy', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/st-martin-and-st-barthelemy/entry-requirements">Link</a>'},
  {Country:'St Pierre and Miquelon', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/st-pierre-and-miquelon/entry-requirements">Link</a>'},
  {Country:'St Vincent and The Grenadines', 'Quarantine on arrival':'Complex', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/st-vincent-and-the-grenadines/entry-requirements">Link</a>'},
  {Country:'Cambodia', 'Quarantine on arrival':'Complex', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/cambodia/entry-requirements">Link</a>'},
  {Country:'New Caledonia', 'Quarantine on arrival':'Complex', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/new-caledonia/entry-requirements">Link</a>'},
  {Country:'South Korea', 'Quarantine on arrival':'14 Day', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/south-korea/entry-requirements">Link</a>'},
  {Country:'Wallis and Futuna', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/wallis-and-fotuna/entry-requirements">Link</a>'},
  {Country:'Reunion', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/reunion/entry-requirements">Link</a>'},
 ];
const USA = [
  {Country:'USA', 'Quarantine on arrival':'Dependent on State', 'Person 1 Entry Info':'<a href="https://www.cdc.gov/coronavirus/2019-ncov/travelers/from-other-countries.html">Link</a>'},
  {Country:'French Polynesia', 'Quarantine on arrival':'Requires proof of negative test', 'Person 1 Entry Info':'<a href="https://fj.usembassy.gov/u-s-citizen-services/covid-19-information/">Link</a>'},
  {Country:'Antigua and Barbuda', 'Quarantine on arrival':'Test required', 'Person 1 Entry Info':'<a href="https://visitantiguabarbuda.com/travel-advisory/">Link</a>'},
  {Country:'Armenia', 'Quarantine on arrival':'14 day Quarantine or Negative Test', 'Person 1 Entry Info':'<a href="https://am.usembassy.gov/u-s-citizen-services/covid-19-information/">Link</a>'},
  {Country:'Aruba', 'Quarantine on arrival':'Test Required', 'Person 1 Entry Info':'<a href="https://cw.usconsulate.gov/news-events/covid-19-information/">Link</a>'},
  {Country:'Barbados', 'Quarantine on arrival':'Test and quarantine required', 'Person 1 Entry Info':'<a href="https://bb.usembassy.gov/u-s-citizen-services/covid-19-information/">Link</a>'},
  {Country:'Benin', 'Quarantine on arrival':'Test Required', 'Person 1 Entry Info':'<a href="https://bj.usembassy.gov/info-covid19/">Link</a>'},
  {Country:'Bermuda', 'Quarantine on arrival':'Test Required', 'Person 1 Entry Info':'<a href="https://bm.usconsulate.gov/covid-19-information/">Link</a>'},
  {Country:'Chad', 'Quarantine on arrival':'Test Required', 'Person 1 Entry Info':'<a href="https://td.usembassy.gov/covid-19-information/">Link</a>'},
  {Country:'Cote dIvoire', 'Quarantine on arrival':'14 day Quarantine', 'Person 1 Entry Info':'<a href="https://ci.usembassy.gov/covid-19-information/">Link</a>'},
  {Country:'Croatia', 'Quarantine on arrival':'Test Required', 'Person 1 Entry Info':'<a href="https://hr.usembassy.gov/covid-19-information-2/">Link</a>'},
  {Country:'Dominica', 'Quarantine on arrival':'Requires testing', 'Person 1 Entry Info':'<a href="https://bb.usembassy.gov/u-s-citizen-services/covid-19-information/">Link</a>'},
  {Country:'Ecuador', 'Quarantine on arrival':'14 Days', 'Person 1 Entry Info':'<a href="https://ec.usembassy.gov/covid-19-information-ecu-2/">Link</a>'},
  {Country:'Equatorial Guinea', 'Quarantine on arrival':'Test Required', 'Person 1 Entry Info':'<a href="https://gq.usembassy.gov/covid-19-information/">Link</a>'},
  {Country:'Guinea', 'Quarantine on arrival':'Test Required', 'Person 1 Entry Info':'<a href="https://gn.usembassy.gov/u-s-citizen-services/covid-19-information/">Link</a>'},
  {Country:'Hungary', 'Quarantine on arrival':'Test Required', 'Person 1 Entry Info':'<a href="https://hu.usembassy.gov/covid-19/">Link</a>'},
  {Country:'Ireland', 'Quarantine on arrival':'14 day Quarantine', 'Person 1 Entry Info':'<a href="https://ie.usembassy.gov/covid-19-information/">Link</a>'},
  {Country:'Jamaica', 'Quarantine on arrival':'Test Required', 'Person 1 Entry Info':'<a href="https://www.visitjamaica.com/travelauthorization/">Link</a>'},
  {Country:'Kenya', 'Quarantine on arrival':'Test Required', 'Person 1 Entry Info':'<a href="https://ke.usembassy.gov/covid-19-information/">Link</a>'},
  {Country:'Liechtenstein', 'Quarantine on arrival':'10 day Quarantine', 'Person 1 Entry Info':'<a href="https://ch.usembassy.gov/embassy/liechtenstein/u-s-citizenship-services/covid-19-faq/">Link</a>'},
  {Country:'Maldives', 'Quarantine on arrival':'Unsure', 'Person 1 Entry Info':'<a href="https://immigration.gov.mv/">Link</a>'},
  {Country:'Nauru', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'<a href="https://fj.usembassy.gov/u-s-citizen-services/covid-19-information/">Link</a>'},
  {Country:'New Caledonia', 'Quarantine on arrival':'14 days', 'Person 1 Entry Info':'<a href="https://fj.usembassy.gov/u-s-citizen-services/covid-19-information/">Link</a>'},
  {Country:'Niger', 'Quarantine on arrival':'Test Required', 'Person 1 Entry Info':'<a href="https://ne.usembassy.gov/u-s-citizen-services/covid-19-information/">Link</a>'},
  {Country:'North Macedonia', 'Quarantine on arrival':'None', 'Person 1 Entry Info':'<a href="https://mk.usembassy.gov/covid-19-information/">Link</a>'},
  {Country:'Saint Lucia', 'Quarantine on arrival':'Quarantine and Test Required', 'Person 1 Entry Info':'<a href="https://bb.usembassy.gov/u-s-citizen-services/covid-19-information/">Link</a>'},
  {Country:'Saint Vincent and The Grenadines', 'Quarantine on arrival':'5 day Quarantine and Test Required', 'Person 1 Entry Info':'<a href="https://bb.usembassy.gov/u-s-citizen-services/covid-19-information/">Link</a>'},
  {Country:'Senegal', 'Quarantine on arrival':'Test Required', 'Person 1 Entry Info':'<a href="https://sn.usembassy.gov/covid-19-information/">Link</a>'},
  {Country:'Serbia', 'Quarantine on arrival':'None', 'Person 1 Entry Info':'<a href="https://rs.usembassy.gov/serbia-covid-19-information/">Link</a>'},
  {Country:'Sint Maarten', 'Quarantine on arrival':'Test Required', 'Person 1 Entry Info':'<a href="https://cw.usconsulate.gov/news-events/covid-19-information/">Link</a>'},
  {Country:'South Korea', 'Quarantine on arrival':'14 day Quarantine', 'Person 1 Entry Info':'<a href="https://kr.usembassy.gov/022420-covid-19-information/">Link</a>'},
  {Country:'Switzerland', 'Quarantine on arrival':'10 day Quarantine', 'Person 1 Entry Info':'<a href="https://ch.usembassy.gov/embassy/liechtenstein/u-s-citizenship-services/covid-19-faq/">Link</a>'},
  {Country:'Togo', 'Quarantine on arrival':'Test and Visa Required', 'Person 1 Entry Info':'<a href="https://tg.usembassy.gov/u-s-citizen-services/security-and-travel-information/covid-19/">Link</a>'},
  {Country:'Turkey', 'Quarantine on arrival':'None', 'Person 1 Entry Info':'<a href="https://tr.usembassy.gov/covid-19-information-2/">Link</a>'},
  {Country:'Turks and Caicos Islands', 'Quarantine on arrival':'Test Required and 14 day Quarantine', 'Person 1 Entry Info':'<a href="https://bs.usembassy.gov/covid-19-information/">Link</a>'},
  {Country:'Ukraine', 'Quarantine on arrival':'Test or Quarantine', 'Person 1 Entry Info':'<a href="https://ua.usembassy.gov/covid-19-information/">Link</a>'},
  {Country:'United Arab Emirates', 'Quarantine on arrival':'Test Required', 'Person 1 Entry Info':'<a href="https://ae.usembassy.gov/u-s-citizen-services/covid-19-information/">Link</a>'},
  {Country:'United Kingdom', 'Quarantine on arrival':'14 day Quarantine', 'Person 1 Entry Info':'<a href="https://uk.usembassy.gov/covid-19-coronavirus-information/">Link</a>'},
  {Country:'Mozambique', 'Quarantine on arrival':'Test required and 10 day Quarantine', 'Person 1 Entry Info':'<a href="https://mz.usembassy.gov/covid-19-information/">Link</a>'},
   ];
// const EU = [
//     {Country:'United Kingdom', 'Quarantine on arrival':'14 Day', 'Person 1 Entry Info':'visit gov.uk/'},
//     {Country:'Croatia', 'Quarantine on arrival':'14 Day', 'Person 1 Entry Info':'visit us.gov.croatia'},
//     {Country:'Ireland', 'Quarantine on arrival':'0 Day', 'Person 1 Entry Info':'visit gov.uk/'},
//     {Country:'European Union', 'Quarantine on arrival':'0 Day', 'Person 1 Entry Info':'visit gov.uk/'},
//  ];
// const IRL = [
//     {Country:'United Kingdom', 'Quarantine on arrival':'14 Day', 'Person 1 Entry Info':'visit gov.uk/'},
//     {Country:'European Union', 'Quarantine on arrival':'0 Day', 'Person 1 Entry Info':'visit gov.uk/'},
//     {Country:'Ireland', 'Quarantine on arrival':'0 Day', 'Person 1 Entry Info':'visit gov.uk/'}
//  ];

const options = ["UK", "USA"];
