const UK = [
  {Country:'United Kingdom', 'Quarantine on arrival':'n/a', 'Person 1 Entry Info':'n/a'},
  {Country:'Austria', 'Quarantine on arrival':'None', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/austria/entry-requirements">Link</a>'},
  {Country:'Croatia', 'Quarantine on arrival':'None', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/croatia/entry-requirements">Link</a>'},
  {Country:'Cyprus', 'Quarantine on arrival':'PCR 72hrs prior', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/cyprus/entry-requirements">Link</a>'},
  {Country:'Czech Republic', 'Quarantine on arrival':'None', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/czech-republic/entry-requirements">Link</a>'},
  {Country:'Denmark', 'Quarantine on arrival':'None', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/denmark/entry-requirements">Link</a>'},
  {Country:'Estonia', 'Quarantine on arrival':'None', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/estonia/entry-requirements">Link</a>'},
  {Country:'Germany', 'Quarantine on arrival':'None', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/germany/entry-requirements">Link</a>'},
  {Country:'Gibraltar', 'Quarantine on arrival':'None', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/gibraltar/entry-requirements">Link</a>'},
  {Country:'Greece', 'Quarantine on arrival':'Complex', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/greece/entry-requirements">Link</a>'},
  {Country:'Hungary', 'Quarantine on arrival':'2 x PCR prior', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/hungary/entry-requirements">Link</a>'},
  {Country:'Iceland', 'Quarantine on arrival':'PCR on arrival', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/iceland/entry-requirements">Link</a>'},
  {Country:'Ireland', 'Quarantine on arrival':'14 Day', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/ireland/entry-requirements">Link</a>'},
  {Country:'Italy', 'Quarantine on arrival':'None', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/italy/entry-requirements">Link</a>'},
  {Country:'Latvia', 'Quarantine on arrival':'14 Day', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/latvia/entry-requirements">Link</a>'},
  {Country:'Liechtenstein', 'Quarantine on arrival':'None', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/liechtenstein/entry-requirements">Link</a>'},
  {Country:'Lithuania', 'Quarantine on arrival':'None', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/lithuania/entry-requirements">Link</a>'},
  {Country:'Norway', 'Quarantine on arrival':'None', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/norway/entry-requirements">Link</a>'},
  {Country:'Poland', 'Quarantine on arrival':'None', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/poland/entry-requirements">Link</a>'},
  {Country:'Portugal (only The Azores and Madeira)', 'Quarantine on arrival':'Complex', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/portugal/entry-requirements">Link</a>'},
  {Country:'San Marino', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/san-marino/entry-requirements">Link</a>'},
  {Country:'Slovakia', 'Quarantine on arrival':'None', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/slovakia/entry-requirements">Link</a>'},
  {Country:'Slovenia', 'Quarantine on arrival':'None', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/slovenia/entry-requirements">Link</a>'},
  {Country:'Switzerland', 'Quarantine on arrival':'None', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/poland/entry-requirements">Link</a>'},
  {Country:'Turkey', 'Quarantine on arrival':'None', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/turkey/entry-requirements">Link</a>'},
  {Country:'Antigua & Barbuda', 'Quarantine on arrival':'Complex', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/antigua-and-barbuda/entry-requirements">Link</a>'},
  {Country:'Barbados', 'Quarantine on arrival':'PCR prior, complex', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/barbados/entry-requirements">Link</a>'},
  {Country:'Bermuda', 'Quarantine on arrival':'Complex', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/bermuda/entry-requirements">Link</a>'},
  {Country:'Cuba', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/cuba/entry-requirements">Link</a>'},
  {Country:'Curaçao', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/curacao/entry-requirements">Link</a>'},
  {Country:'Dominica', 'Quarantine on arrival':'PCR Prior', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/dominica/entry-requirements">Link</a>'},
  {Country:'Falkland Islands', 'Quarantine on arrival':'14 Days', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/falkland-islands/entry-requirements">Link</a>'},
  {Country:'Grenada', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/grenada/entry-requirements">Link</a>'},
  {Country:'Guadeloupe', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/guadeloupe/entry-requirements">Link</a>'},
  {Country:'Jamaica', 'Quarantine on arrival':'Complex', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/jamaica/entry-requirements">Link</a>'},
  {Country:'Martinique', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/martinique/entry-requirements">Link</a>'},
  {Country:'South Georgia & the South Sandwich Islands', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/south-georgia-and-south-sandwich-islands/entry-requirements">Link</a>'},
  {Country:'St Lucia', 'Quarantine on arrival':'Complex', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/st-lucia/entry-requirements">Link</a>'},
  {Country:'St Maarten', 'Quarantine on arrival':'PCR 72hrs prior', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/st-maarten/entry-requirements">Link</a>'},
  {Country:'St Martin and St Barthélemy', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/st-martin-and-st-barthelemy/entry-requirements">Link</a>'},
  {Country:'St Pierre and Miquelon', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/st-pierre-and-miquelon/entry-requirements">Link</a>'},
  {Country:'St Vincent and The Grenadines', 'Quarantine on arrival':'Complex', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/st-vincent-and-the-grenadines/entry-requirements">Link</a>'},
  {Country:'Cambodia', 'Quarantine on arrival':'Complex', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/cambodia/entry-requirements">Link</a>'},
  {Country:'New Caledonia', 'Quarantine on arrival':'Complex', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/new-caledonia/entry-requirements">Link</a>'},
  {Country:'South Korea', 'Quarantine on arrival':'14 Day', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/south-korea/entry-requirements">Link</a>'},
  {Country:'Wallis and Futuna', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/wallis-and-fotuna/entry-requirements">Link</a>'},
  {Country:'Reunion', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'<a href="https://www.gov.uk/foreign-travel-advice/reunion/entry-requirements">Link</a>'},
 ];
const USA = [
  {Country:'USA', 'Quarantine on arrival':'Dependent on State', 'Person 1 Entry Info':'<a href="https://www.cdc.gov/coronavirus/2019-ncov/travelers/from-other-countries.html">Link</a>'},
  {Country:'French Polynesia', 'Quarantine on arrival':'Requires proof of negative test', 'Person 1 Entry Info':'<a href="https://fj.usembassy.gov/u-s-citizen-services/covid-19-information/">Link</a>'},
  {Country:'Antigua and Barbuda', 'Quarantine on arrival':'Test required', 'Person 1 Entry Info':'<a href="https://visitantiguabarbuda.com/travel-advisory/">Link</a>'},
  {Country:'Armenia', 'Quarantine on arrival':'14 day Quarantine or Negative Test', 'Person 1 Entry Info':'<a href="https://am.usembassy.gov/u-s-citizen-services/covid-19-information/">Link</a>'},
  {Country:'Aruba', 'Quarantine on arrival':'Test Required', 'Person 1 Entry Info':'<a href="https://cw.usconsulate.gov/news-events/covid-19-information/">Link</a>'},
  {Country:'Barbados', 'Quarantine on arrival':'Test and quarantine required', 'Person 1 Entry Info':'<a href="https://bb.usembassy.gov/u-s-citizen-services/covid-19-information/">Link</a>'},
  {Country:'Benin', 'Quarantine on arrival':'Test Required', 'Person 1 Entry Info':'<a href="https://bj.usembassy.gov/info-covid19/">Link</a>'},
  {Country:'Bermuda', 'Quarantine on arrival':'Test Required', 'Person 1 Entry Info':'<a href="https://bm.usconsulate.gov/covid-19-information/">Link</a>'},
{Country:'Chad', 'Quarantine on arrival':'Test Required', 'Person 1 Entry Info':'<a href="https://td.usembassy.gov/covid-19-information/">Link</a>'},
{Country:'Cote dIvoire', 'Quarantine on arrival':'14 day Quarantine', 'Person 1 Entry Info':'<a href="https://ci.usembassy.gov/covid-19-information/">Link</a>'},
{Country:'Croatia', 'Quarantine on arrival':'Test Required', 'Person 1 Entry Info':'<a href="https://hr.usembassy.gov/covid-19-information-2/">Link</a>'},
{Country:'Dominica', 'Quarantine on arrival':'Requires testing', 'Person 1 Entry Info':'<a href="https://bb.usembassy.gov/u-s-citizen-services/covid-19-information/">Link</a>'},
{Country:'Ecuador', 'Quarantine on arrival':'14 Days', 'Person 1 Entry Info':'<a href="https://ec.usembassy.gov/covid-19-information-ecu-2/">Link</a>'},
{Country:'Equatorial Guinea', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Eritrea', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Estonia', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Finland', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'France', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'French West Indies', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Gabon', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Georgia', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Germany', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Ghana', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Greece', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Guinea', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Guinea-Bissau', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Hungary', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Iceland', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Ireland', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Israel, The West Bank and Gaza', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Italy', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Jamaica', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Japan', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Jordan', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Kenya', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Kuwait', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Laos', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Latvia', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Lebanon', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Lesotho', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Liberia', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Liechtenstein', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Lithuania', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Luxembourg', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Madagascar', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Malaysia', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Maldives', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Malta', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Marshall Islands', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Mauritania', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Micronesia', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Moldova', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Montenegro', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Morocco', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Nauru', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'<a href="https://fj.usembassy.gov/u-s-citizen-services/covid-19-information/">Link</a>'},
{Country:'Nepal', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Netherlands', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'New Caledonia', 'Quarantine on arrival':'14 days', 'Person 1 Entry Info':'<a href="https://fj.usembassy.gov/u-s-citizen-services/covid-19-information/">Link</a>'},
{Country:'Niger', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Nigeria', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'North Macedonia', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Norway', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Pakistan', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Palau', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Papua New Guinea', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Paraguay', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Philippines', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Poland', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Portugal', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Qatar', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Republic of the Congo', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Romania', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Rwanda', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Saint Lucia', 'Quarantine on arrival':'Quarantine and Test Required', 'Person 1 Entry Info':'<a href="https://bb.usembassy.gov/u-s-citizen-services/covid-19-information/">Link</a>'},
{Country:'Saint Vincent and The Grenadines', 'Quarantine on arrival':'5 day Quarantine and Test Required', 'Person 1 Entry Info':'<a href="https://bb.usembassy.gov/u-s-citizen-services/covid-19-information/">Link</a>'},
{Country:'Samoa', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Senegal', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Serbia', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Seychelles', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Sierra Leone', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Singapore', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Sint Maarten', 'Quarantine on arrival':'Test Required', 'Person 1 Entry Info':'<a href="https://cw.usconsulate.gov/news-events/covid-19-information/">Link</a>'},
{Country:'Slovakia', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Slovenia', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Solomon Island', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'South Africa', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'South Korea', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Sri Lanka', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Sudan', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Suriname', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Sweden', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Switzerland', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Tanzania', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'The Gambia', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Timor-Leste', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Togo', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Trinidad and Tobago', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Tunisia', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Turkey', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Turks and Caicos Islands', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Uganda', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Ukraine', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'United Arab Emirates', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'United Kingdom', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Uruguay', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Uzbekistan', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Vanuatu', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Vietnam', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Zambia', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Zimbabwe', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
{Country:'Mozambique', 'Quarantine on arrival':'Unknown', 'Person 1 Entry Info':'n/a'},
 ];
// const EU = [
//     {Country:'United Kingdom', 'Quarantine on arrival':'14 Day', 'Person 1 Entry Info':'visit gov.uk/'},
//     {Country:'Croatia', 'Quarantine on arrival':'14 Day', 'Person 1 Entry Info':'visit us.gov.croatia'},
//     {Country:'Ireland', 'Quarantine on arrival':'0 Day', 'Person 1 Entry Info':'visit gov.uk/'},
//     {Country:'European Union', 'Quarantine on arrival':'0 Day', 'Person 1 Entry Info':'visit gov.uk/'},
//  ];
// const IRL = [
//     {Country:'United Kingdom', 'Quarantine on arrival':'14 Day', 'Person 1 Entry Info':'visit gov.uk/'},
//     {Country:'European Union', 'Quarantine on arrival':'0 Day', 'Person 1 Entry Info':'visit gov.uk/'},
//     {Country:'Ireland', 'Quarantine on arrival':'0 Day', 'Person 1 Entry Info':'visit gov.uk/'}
//  ];

const options = ["UK", "USA"];
